server:
  port: 9094

spring:
  application:
    name: Config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ayushdgupta/SpringBoot3-ConfigFiles-ConfigServer-Microservice
          clone-on-start: true
